# Generated by Django 4.2 on 2023-04-21 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Description')),
                ('calo', models.FloatField(verbose_name='Calo')),
                ('time', models.TimeField(verbose_name='time')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.food', verbose_name='food')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ingredient', verbose_name='ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='ings',
            field=models.ManyToManyField(through='backend.Food_Ingredient', to='backend.ingredient', verbose_name='nguyen lieu'),
        ),
    ]
