# Generated by Django 4.2.1 on 2023-05-04 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('step', models.TextField(verbose_name='Step')),
                ('picture', models.ImageField(null=True, upload_to='about', verbose_name='picture')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('calo', models.FloatField(verbose_name='Calo')),
                ('time', models.CharField(max_length=50, verbose_name='Time')),
                ('introduce', models.TextField(verbose_name='Introduce')),
                ('number_of_ingredients', models.IntegerField(verbose_name='number_of_ingredients')),
                ('picture', models.ImageField(upload_to='Food', verbose_name='picture')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('measure', models.CharField(max_length=50, verbose_name='Measure')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.food', verbose_name='food')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='backend.type', verbose_name='type')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=50, verbose_name='Amount')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.food', verbose_name='food')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.ingredient', verbose_name='ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Food_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='backend.about', verbose_name='about')),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.food', verbose_name='food')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='ings1',
            field=models.ManyToManyField(related_name='ingredient', through='backend.Food_Ingredient', to='backend.ingredient', verbose_name='nguyen lieu'),
        ),
        migrations.AddField(
            model_name='food',
            name='ings2',
            field=models.ManyToManyField(through='backend.Food_Type', to='backend.type', verbose_name='loai nguyen lieu'),
        ),
        migrations.AddField(
            model_name='food',
            name='ings3',
            field=models.ManyToManyField(through='backend.Food_About', to='backend.about', verbose_name='cac buoc nau'),
        ),
    ]
