# Generated by Django 4.2 on 2023-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='picture',
            field=models.ImageField(null=True, upload_to='about', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(upload_to='Food', verbose_name='picture'),
        ),
    ]
